config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :article_id,
    primary_key: :id
  )

  has_many(
    :taggings,
    class_name: "Tagging",
    foreign_key: :article_id,
    primary_key: :id
  )

  has_many(
    :tags,
    through: :taggings,
    source:  :tag
  )


  def tag_list
    self.tags.join(", ")
  end

  def tag_list=(tags_string)
    tags_array = tags_string.downcase.split(", ").uniq

    self.tags = tags_array.map do |tag_name|
      Tag.find_or_create_by(name: tag_name)
    end

    self
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  author_name :string           not null
#  body        :text             not null
#  article_id  :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to(
    :article,
    class_name: "Article",
    foreign_key: :article_id,
    primary_key: :id
  )
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  has_many(
    :taggings,
    class_name: "Tagging",
    foreign_key: :tag_id,
    primary_key: :id
  )

  has_many(
    :articles,
    through: :taggings,
    source: :article
  )


  def to_s
    name
  end
end

app/models/tagging.rb
# == Schema Information
#
# Table name: taggings
#
#  id         :integer          not null, primary key
#  tag_id     :integer          not null
#  article_id :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tagging < ActiveRecord::Base
  belongs_to(
    :tag,
    class_name: "Tag",
    foreign_key: :tag_id,
    primary_key: :id
  )

  belongs_to(
    :article,
    class_name: "Article",
    foreign_key: :article_id,
    primary_key: :id
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def create
    @article = Article.create(article_params)
    flash.notice = "Article '#{@article.title}' Created!"

    redirect_to article_path(@article)
  end

  def destroy
    Article.find(params[:id]).destroy
    flash.notice = "Article '#{@article.title}' Deleted."

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article_id
  end


  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end


  private
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %> </h4>
  <p class="comment"><%= comment.body %></p>
  <p>
    <%= distance_of_time_in_words(comment.article.created_at,
        comment.created_at)%> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article<h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article),
        class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
</ul>


<%= link_to "Create new article", new_article_path,
  class: "new_article"%>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<ul>
  <% @article.errors.full_messages.each do |error| %>
    <li> <%= error %> </li>
  <% end %>
</ul>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<p>
  <% @article.tags.each do |tag| %>
    <%= link_to tag.to_s, tag_path(tag) %>
  <% end %>
</p>

<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "edit", edit_article_path(@article) %>
<%= link_to "delete", article_path(@article), method: :delete,
            data: {confirm: "Really delete the article?"} %>

<h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<p>
<%= form_for([@article, @comment]) do |f| %>
  <p>
     <%= f.label :author_name, "Your Name" %>
     <%= f.text_field :author_name %>
   </p>
   <p>
     <%= f.label :body %>
     <%= f.text_area :body %>
   </p>
   <p>
     <%= f.submit 'Submit' %>
   </p>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="flash"><%= flash.notice %></p>

<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>All tags</h1>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1> Articles Tagged with '<%= @tag.name %>'' </h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>